name: Auto-generate Blog Post

on:
  schedule:
    - cron: '0 0 * * *' # 日本時間 午前9時
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをチェックアウト（push 用の権限付き）
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Node.js 環境セットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 依存パッケージをインストール
      - name: Install dependencies
        run: npm ci

      # 4. 記事自動生成スクリプトを実行
      - name: Generate posts
        run: node scripts/generate-post.js

      # 5. 変更の検出とコミット（変更があれば）
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add posts
            git commit -m "chore: auto-gen posts for $(date +'%Y-%m-%d')"
            git push origin HEAD:master
          else
            echo "No changes to commit"
          fi
