name: Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master # または main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
